name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-test:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Check Code Formatting
        run: npm run format:check

      - name: Run Unit & Integration Tests
        run: npm run test -- --coverage

      - name: Build the Project
        run: npm run build
