name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  lint-test-build:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Debug Secrets (Check if DB_HOST is Available)
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
        run: echo "DB_HOST is set"

      - name: Run Tests with Database
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: npm run test -- --coverage

      - name: Build the Project
        run: npm run build
