name: Lighthouse CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build the Project
        run: npm run build

      - name: Start Server
        run: npm run start & sleep 5

      - name: Run Lighthouse Audit
        run: |
          npx lighthouse http://localhost:3000 --output html --output-path ./lighthouse-report.html

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse_results
          path: ./lighthouse-report.html
